// app/layout.tsx

import type { Metadata } from "next";
import "../styles/globals.css";
import Header from "@/components/Header"; // Import the Header component

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Header /> {/* Render the Header component at the top */}
        {children} {/* Page content will render below the Header */}
      </body>
    </html>
  );
}